       IDENTIFICATION DIVISION.
       PROGRAM-ID. TOTAL-MATCH-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "TOTAL-MATCH.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC X(100).

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-LST1 OCCURS 2 TIMES INDEXED BY NI PIC X(2).
           05 L-LST2 OCCURS 2 TIMES INDEXED BY NJ PIC X(2).
           05 RESULT OCCURS 100 TIMES INDEXED BY NK PIC X(100).

       PROCEDURE DIVISION.

       MOVE '4' TO L-LST1(1)
       MOVE '5' TO L-LST1(2)
       MOVE '1' TO L-LST2(1)
       MOVE '2' TO L-LST2(2)
       MOVE '3' TO L-LST2(3)
       MOVE '4' TO L-LST2(4)

       CALL "TOTAL-MATCH" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       PERFORM VARYING NK FROM 1 BY 1 UNTIL NK > 100
           MOVE RESULT (NK) TO OUTPUT-RECORD
           WRITE OUTPUT-RECORD
       END-PERFORM

        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       