       IDENTIFICATION DIVISION.
       PROGRAM-ID. COMPARE-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "COMPARE.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC S9(10) SIGN LEADING.

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-GAME OCCURS 6 TIMES INDEXED BY NI PIC S9(10).
           05 L-GUESS OCCURS 6 TIMES INDEXED BY NJ PIC S9(10).
           05 RESULT OCCURS 100 TIMES INDEXED BY NK PIC S9(10).

       PROCEDURE DIVISION.

       MOVE 0 TO L-GAME(1)
       MOVE 0 TO L-GAME(2)
       MOVE 0 TO L-GAME(3)
       MOVE 0 TO L-GAME(4)
       MOVE 0 TO L-GAME(5)
       MOVE 0 TO L-GAME(6)
       MOVE 0 TO L-GUESS(1)
       MOVE 0 TO L-GUESS(2)
       MOVE 0 TO L-GUESS(3)
       MOVE 0 TO L-GUESS(4)
       MOVE 0 TO L-GUESS(5)
       MOVE 0 TO L-GUESS(6)

       CALL "COMPARE" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       PERFORM VARYING NK FROM 1 BY 1 UNTIL NK > 100
           MOVE RESULT (NK) TO OUTPUT-RECORD
           WRITE OUTPUT-RECORD
       END-PERFORM

        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       