       IDENTIFICATION DIVISION.
       PROGRAM-ID. INTERSECTION-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "INTERSECTION.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC X(100).

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-INTERVAL1 OCCURS 100 TIMES INDEXED BY NI PIC S9(10).
           05 L-INTERVAL2 OCCURS 100 TIMES INDEXED BY NJ PIC S9(10).
           05 RESULT PIC X(100).

       PROCEDURE DIVISION.

       MOVE -2 TO L-INTERVAL1(1)
       MOVE -2 TO L-INTERVAL1(2)
       MOVE -3 TO L-INTERVAL2(1)
       MOVE -2 TO L-INTERVAL2(2)

       CALL "INTERSECTION" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       MOVE RESULT TO OUTPUT-RECORD
       WRITE OUTPUT-RECORD


        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       