       IDENTIFICATION DIVISION.
       PROGRAM-ID. BELOW-ZERO-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "BELOW-ZERO.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC 9.

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-OPERATIONS OCCURS 8 TIMES INDEXED BY NI PIC S9(10).
           05 RESULT PIC 9.

       PROCEDURE DIVISION.

       MOVE 1 TO L-OPERATIONS(1)
       MOVE -2 TO L-OPERATIONS(2)
       MOVE 2 TO L-OPERATIONS(3)
       MOVE -2 TO L-OPERATIONS(4)
       MOVE 5 TO L-OPERATIONS(5)
       MOVE -5 TO L-OPERATIONS(6)
       MOVE 4 TO L-OPERATIONS(7)
       MOVE -4 TO L-OPERATIONS(8)

       CALL "BELOW-ZERO" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       MOVE RESULT TO OUTPUT-RECORD
       WRITE OUTPUT-RECORD


        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       