       IDENTIFICATION DIVISION.
       PROGRAM-ID. DO-ALGEBRA-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "DO-ALGEBRA.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC S9(10) SIGN LEADING.

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-OPERATOR OCCURS 3 TIMES INDEXED BY NI PIC X(3).
           05 L-OPERAND OCCURS 3 TIMES INDEXED BY NJ PIC S9(10).
           05 RESULT PIC S9(10).

       PROCEDURE DIVISION.

       MOVE '+' TO L-OPERATOR(1)
       MOVE '*' TO L-OPERATOR(2)
       MOVE '-' TO L-OPERATOR(3)
       MOVE 2 TO L-OPERAND(1)
       MOVE 3 TO L-OPERAND(2)
       MOVE 4 TO L-OPERAND(3)
       MOVE 5 TO L-OPERAND(4)

       CALL "DO-ALGEBRA" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       MOVE RESULT TO OUTPUT-RECORD
       WRITE OUTPUT-RECORD


        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       