       IDENTIFICATION DIVISION.
       PROGRAM-ID. EXCHANGE-CALL.

       ENVIRONMENT DIVISION.

       INPUT-OUTPUT SECTION.

       FILE-CONTROL.

       SELECT OUTPUT-FILE ASSIGN TO "EXCHANGE.TXT"
           ORGANIZATION IS LINE SEQUENTIAL
           STATUS IS OUTPUT-FILE-STATUS.
       
       DATA DIVISION.

       FILE SECTION.
       FD OUTPUT-FILE.
       01 OUTPUT-RECORD PIC X(100).

       WORKING-STORAGE SECTION.

       01 OUTPUT-FILE-STATUS PIC X(02).



       01 LINKED-ITEMS.
           05 L-LST1 OCCURS 4 TIMES INDEXED BY NI PIC S9(10).
           05 L-LST2 OCCURS 4 TIMES INDEXED BY NJ PIC S9(10).
           05 RESULT PIC X(100).

       PROCEDURE DIVISION.

       MOVE 1 TO L-LST1(1)
       MOVE 2 TO L-LST1(2)
       MOVE 3 TO L-LST1(3)
       MOVE 4 TO L-LST1(4)
       MOVE 2 TO L-LST2(1)
       MOVE 1 TO L-LST2(2)
       MOVE 4 TO L-LST2(3)
       MOVE 3 TO L-LST2(4)

       CALL "EXCHANGE" USING LINKED-ITEMS
       
       OPEN OUTPUT OUTPUT-FILE

       IF OUTPUT-FILE-STATUS NOT = "00"
           DISPLAY "ERROR OPENING OUTPUT FILE"
           STOP RUN
        END-IF

       MOVE RESULT TO OUTPUT-RECORD
       WRITE OUTPUT-RECORD


        IF OUTPUT-FILE-STATUS NOT = "00"
            DISPLAY "ERROR WRITING TO OUTPUT FILE"
            STOP RUN
        END-IF

        CLOSE OUTPUT-FILE
        .
       